collection_name: agent
persist_directory: E:/AIgoing/rag/chroma_db
k: 3
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: [ "txt", "pdf" ]

chunk_size: 200
chunk_overlap: 20
separators: [ "\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", "" ]

rerank_enabled: True          # 是否启用 rerank
rerank_model: "E:/AIgoing/models/ms-marco-MiniLM-L-6-v2"  # 模型名称
rerank_initial_k: 20          # 向量检索返回的候选文档数量
rerank_final_k: 5             # 最终返回的文档数量
